# aws variables
aws_region = "us-east-2"
# project tags
owner = "gretchen[dot]keppel[at]gmail[dot]com"
project_name = "tf-demo-vpc-ec2"
repo = "https://github.com/grrretchen/demo.terraform-aws-vpc-ec2-public"
# label tags
namespace = "bhl"
environment = "ue2"
stage = "l"
